spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/canjica
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    flyway:
      enabled: true
      locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080

app:
  base-url: http://localhost:8080