CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE tbl_account (
   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
   name VARCHAR(255),
   email VARCHAR(255) NOT NULL UNIQUE,
   cpf VARCHAR(20) NOT NULL UNIQUE
);
